Victor:
  Dataset: 
    Input: "/home/victor/Datasets/ArtForgeryDetection/Split"
    Output:
      Test: "Data/Test"
      Train: "Data/Train"
      
  SIFT: "CustomDescriptors/SiftDescriptor/main"
  FACE: 
    PREDICTOR: "CustomDescriptors/FaceDescriptor/shape_predictor_68_face_landmarks.dat"
    RECOGNITION: "CustomDescriptors/FaceDescriptor/dlib_face_recognition_resnet_model_v1.dat"
  Resnet: "CustomDescriptors/ResnetDescriptor"
